title: "Nav Item"
status: "ready"
context:
  nav:
    items:
      -
        title: Nav item 1
      -
        title: Nav item 2
      -
        title: Nav item 3
  metatitle:
      message: Meta Title
variants:
  -
    name: large
    context:
      navtitle: Lorem ipsum dolor sit
      nav:
        modifier: nav-item--large
        items:
          -
            title: Large nav item 1
          -
            title: Large nav item 2
          -
            title: Large nav item 3
      metatitle:
          message: Large Meta Title
  -
    name: inline
    context:
      nav:
        modifier: nav-item--inline
        items:
          -
            title: How to use this guide
          -
            title: About
      metatitle: false
