title: "Listing Page - Grid Layout"
status: "ready"

context:
  preview:
    noPad: true
  # Hero Context
  hero:
    heading: Pattern category title
    breadcrumbs: true

  # Section Listings
  sections:
      items:
      -
        title: Patterns
        subtitle: All patterns in this section
        description: Nullam id dolor id nibh ultricies vehicula ut id elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Maecenas faucibus mollis interdum. Fusce dapibus.
        meta: Process

        # Items within this Section Listing
        items:
          -
            title: Entries
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: First time contributions
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Making changes
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Reviews
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Evidence
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Expertise and rights
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
