title: "Nav Mobile"
context:
  nav:
    open: true
    items:
    -
      title: Home
      active: true
    -
      title: Patterns
      active: false
    -
      title: About
      active: false
    -
      title: Contribute
      active: false
