title: "Content Page Layout"
status: "ready"

context:
  preview:
    noPad: true
  # Hero Context
  hero:
    heading: About
    breadcrumbs: true
    sidenav: true

  # Hero Lede
  lede:
    message: 'Some introductory text lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vulputate magna velit. Vestibulum fermentum fermentum libero. Vestibulum dui dui, pulvinar bibendum nulla eget, lacinia fermentum lorem.'

  # Nav context
  nav: false

