title: "Meta Title"
collated: false
context:
  metatitle:
    message: Meta Title
variants:
  -
    name: Secondary
    preview: "@preview-dark"
    context:
      metatitle:
          modifier: secondary
  -
    name: White
    preview: "@preview-dark"
    context:
      metatitle:
          modifier: white
