title: "Hero "
status: "ready"
context:
  hero:
    heading: Page Title
    sidenav: true
    breadcrumbs: true
    lowernav: false
  nav:
    modifier: m-nav--large
    items:
    -
      title: Fusce dapibus, tellus ac cursus commodo
    -
      title: Tortor mauris condimentum nibh 
    -
      title: Ut fermentum massa justo sit amet risus
  metatitle:
    message: Introduction
  navtitle: Getting started
  navintro: Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum..
  # pill:
  #   message: Case Study
  lede:
    message: 'Nullam id dolor id nibh ultricies vehicula ut id elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Maecenas faucibus mollis interdum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod.'

variants:
  -
    name: With background image
    context:
      wrapperModifier: bg
      backgroundImage: https://images.unsplash.com/6/blurred_lines.jpeg?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80
  -
    name: soundcloud
    context:
      modifier: soundcloud
  -
    name: infographic
    context:
      modifier: infographic
