title: "Modal"
context:
  modal:
    heading: Suggest a change or addition
    meta: Contribute
    content: '<form method="post" enctype="multipart/form-data" action="#" data-ajax-form>
                <div data-form-message></div>
                <div class="control">
                    <label class="label" for="contrib-form-labels">I want to&hellip;</label>
                    <div class="select__wrapper">
                        <select class="select" name="labels[]" id="contrib-form-labels">
                            
                            <option value="enhancement" selected >Make a suggestion</option>
                            
                            <option value="bug"  >Report an error or bug</option>
                            
                            <option value="question"  >Ask a question</option>
                            
                        </select>
                    </div>
                </div>
                <div class="control">
                    <label class="label" for="contrib-form-title">Give us a brief summary in 100 characters or less (required)</label>

                    <input type="text" id="contrib-form-title" name="title" class="input " placeholder="Title " required>

                </div>
                <div class="control">
                    <label class="label" for="contrib-form-body">Tell us more (required)</label>

                    <textarea class="input" name="body" id="contrib-form-body" rows="5" placeholder="Describe your issue, question or proposed change in more detail here..." required></textarea>

                </div>
                <div class="control">
                    <label class="label" for="contrib-form-uploads">Upload suggested content</label>

                    <input type="file" multiple id="contrib-form-uploads" name="uploads">
                </div>
                <div class="control">
                    <input type="checkbox" class="checkbox" id="contrib-form-terms" name="terms" value="accepted" required>
                    <label for="contrib-form-terms">I am the author/copyright holder of this content and agree to it being published under an <a class="link link--bold" href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC Attribution-ShareAlike 4.0 International License</a> (required)</label>
                </div>
                <div class="control">

                    <input type="submit" value="Submit" class="btn">
                </div>
            </form>'
    open: true
