title: "Section Listing"
status: "ready"
context:
    sections:
        items:
        -
          title: Find patterns
          items:
          -
            title: In vitae mauris
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Vestibulum congue ligula
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Quis suscipit tortor
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Sed justo
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
variants:
    -
        name: short
        context:
            modifier: m-section-listing--short
            message: Shorthand listing items
    -
        name: long-grid
        context:
            modifier: m-section-listing--long-grid
            message: Long listing items within a grid
    -
        name: long-full
        context:
            modifier: m-section-long-full
            message: Long listing items full width