title: "Section Listing"
status: "ready"
context:
    sections:
        items:
        -
          title: Patterns
          items:
          -
            title: Entries
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: First time contributions
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Making changes
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Reviews
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Evidence
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
          -
            title: Expertise and rights
            description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
variants:
    -
        name: short
        context:
            modifier: m-section-listing--short
            message: Shorthand listing items
    -
        name: long-grid
        context:
            modifier: m-section-listing--long-grid
            message: Long listing items within a grid
    -
        name: long-full
        context:
            modifier: m-section-long-full
            message: Long listing items full width