title: "Case Study Layout"
status: "ready"

context:
  preview:
    noPad: true
  # Hero Context
  hero:
    heading: Page Title
    breadcrumbs: true
    sidenav: true

  # Hero Heading Pill
  pill:
    message: Case Study

  # Hero Lede
  lede:
    message: 'A case study of Page Title and General Transit Feed Specification Real-Time (GTFS-RT) extension to support organisations developing or thinking of developing open standards for data.
Our standards case studies provide a summary of the history, development process, governance and key actors involved in the development of an open standard for data.'

  # Nav Context
  nav:
    modifier: m-nav--large
    items:
    -
      title: Nav Item 1
    -
      title: Nav Item 2
    -
      title: Nav Item 3

  # Nav Metatitle
  metatitle:
    message: Something
