title: "Breadcrumb"
status: "ready"
context:
    breadcrumb:
        items:
            -
                title: Home
                active: false
            -
                title: About
                active: false
            -
                title: Content page
                active: true
