title: "Hero Infographic"
status: "ready"
context:
  hero:
    heading: The Open Standards Process
    sidenav: true
    breadcrumbs: true
    lowernav: false
  nav:
    modifier: m-nav--large
    items:
      -
        title: Nav Item 1
      -
        title: Nav Item 2
      -
        title: Nav Item 3
  metatitle:
    message: Lorem
  pill:
    message: Case Study
  lede:
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel velit sed dolor aliquam viverra eget in es.Mauris sed ullamcorper elit, in hendrerit augue. Nunc sodales mauris a ullamcorper pellentesque. Morbi lobortis eleifend nulla non interdum. Lorem ipsum dolor sit amet consecteteur adipicising elit'
