title: "CTA"
status: "ready"
context:
  cta:
    message: Something missing? <a class="link link--bold" href="#">Suggest a change or addition</a>
variants:
  -
    name: white
    context:
      color: white