title: "Nav - Large"
status: "ready"
context:
  navtitle: Lorem ipsum dolor sit
  navintro: Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum.
  nav:
    modifier: nav--large
    items:
      -
        title: Large nav item 1
      -
        title: Large nav item 2
      -
        title: Large nav item 3
  metatitle:
      message: Large Meta Title
