title: "Masthead Nav"
context:
  nav:
    modifier: m-nav--masthead
    items:
    -
      title: Home
      active: false
    -
      title: Patterns
      active: true
    -
      title: About
      active: false
    -
      title: Contribute
      active: false
