title: "Podcast Layout"
status: "ready"

context:
  preview:
    noPad: true
  # Hero Context
  hero:
    lowernav: true

  # Hero Lede
  lede:
    message: 'Some introductory text lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vulputate magna velit. Vestibulum fermentum fermentum libero. Vestibulum dui dui, pulvinar bibendum nulla eget, lacinia fermentum lorem.'

  # Nav Context
  nav:
    pill: true
    modifier: m-nav--large
    items:
    -
      title: Nav Item 1
    -
      title: Nav Item 2
    -
      title: Nav Item 3

  # Nav Title
  navtitle: Introduction to Open Standards

